#!/bin/bash
#
# Grab desktop video and audio -
# - on the middle one of three or the right hand one of two.
#

case "$1" in
    (*)
    ffmpeg -thread_queue_size 512  \
           -f x11grab -r 30 -s 1920x1080 -i :0.0+1920,0 \
           -f pulse -ac 2 -i 2 -q:v 0 /dev/shm/${USER}/dump.mp4
    ;;
esac

#
# Done.
#
