#!/bin/bash
#
# i3player - scripted playback of keyboard and mouse events.
#


#
# Bash script.
#

seconds=0.2s
cat $0 | while read line; do
    case ${line} in
        (:keys*)
        xdotool key --clearmodifiers ${line/:keys /}
        sleep ${seconds}
        ;;
        (:type*)
        string=${line/:type /}
        # Changing the line immediately below this comment will very
        # likely cause spaces to be ignored!
        xdotool type --clearmodifiers "${string}"
        sleep ${seconds}
        ;;
        (:return)
        # This should be separate from the key and text commands,
        # neither of which should include it.
        xdotool key --clearmodifiers Return
        ;;
        (:mouse*)
        # Pass {button x y}. Button is either a single non-zero digit
        # indicating the button to press once, or a dash to indicate
        # that the button isn't pressed. Double click and long press
        # are undefined for the moment.
        button=$(echo $line | awk '{print $2}')
        x=$(echo $line | awk '{print $3}')
        y=$(echo $line | awk '{print $4}')
        xdotool mousemove --sync $x $y
        case ${button} in
            (1|2|3|4|5) xdotool click ${button} ;;
        esac
        ;;
        (:text*)
        # Pass {x y timeout text}. Use it like a transient speech
        # bubble to comment about what's happening.
        x=$(echo $line | awk '{print $2}')
        y=$(echo $line | awk '{print $3}')
        t=$(echo $line | awk '{print $4}')
        message=${line/:text $x $y $t /}
        xdotool mousemove --sync $x $y
        2>&1  yad --mouse --no-buttons \
              --timeout=${t} --timeout-indicator=bottom \
              --title=Comment --text="${message}" | \
            grep -v 'Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.'
        ;;
        (:s)
        ;;
        (:quit)
        exit 0
        ;;
        (*)
        ;;
    esac
done
exit 0

#
# Custom script
#

:text 3333 333 5 Hello World
:quit
:mouse 1 1931 969
:mouse 1 1931 1069
:mouse 4 1931 1069
:mouse 4 1931 1069
:mouse 4 1931 1069
:quit
:keys l s
:return
:type echo hello world
:return
:keys x y


#
# Done.
#
