#!/bin/bash
#
# handbrake-cpulimit
#

handbrake &
echo "Default 200% of total CPU 800%."
sleep 5s
xfce4-terminal -T "Handbrake CPU limiter" -x sudo cpulimit -p $(pidof handbrake) -l ${1:-200}


#
# Done.
#
