#!/bin/bash

echo "The code words in the NATO phonetic alphabet are assigned
to the 26 letters of the English alphabet in alphabetical order
as follows:"
echo ""
echo  "Alfa, Bravo, Charlie, Delta, Echo, Foxtrot, Golf, Hotel,
India, Juliett, Kilo, Lima, Mike, November, Oscar, Papa, Quebec,
Romeo, Sierra, Tango, Uniform, Victor, Whiskey, X-ray, Yankee,
Zulu."



