#!/bin/bash
#
# TSDuck environment (currently 3.17+ git).
#

tsduckroot=/home/shevek/1/packages/tsduck/tsduck-tsduck-3dbf1aa
tstoolspath=${tsduckroot}/src/tstools/release-x86_64
tspluginspath=${tsduckroot}/src/tsplugins/release-x86_64
PATH=${PATH}:

[[ ":$PATH:" != *:${tstoolspath}:* ]] && export  PATH="${tstoolspath}:$PATH"
export LD_LIBRARY_PATH="${tsduckroot}/src/libtsduck/release-x86_64"
export TSPLUGINS_PATH="${tspluginspath}:${tsduckroot}/src/libtsduck"

#
# Done.
#
