#!/bin/bash
#
# A script to start|stop various programs.
#
# - Attention bash gurus!
# - Please tell me if using bash subshells here makes sense or not.
#

# My primary monitor, situated centrally.
cmon=HDMI1


#
# Start here.
#
verb=start
for argument in "${@}"
do
    case "${argument}" in
        # A verb argument affects all subsequent arguments up until
        # either the next verb argument or end-of-list.
        (start|stop)
        verb=${argument}
        ;;

        #
        # Startup and Shutdown.
        #

        (filewatcher)
        if [ "_${verb}" = "_stop" ]; then
            # shellcheck disable=2046
            kill -HUP $(pgrep -f 'i3-wrapper -s')
        fi
        if [ "_${verb}" = "_start" ]; then
            path=$(dirname "$0")
            # Is the eval required?
            (eval "${path}/i3-wrapper --file-watcher") &
            /usr/bin/compton-trans -c -o 70
        fi
        ;;

       (tvheadend)
        if [ "_${verb}" = "_stop" ]; then
            i3-msg --quiet '[title="tvheadend"] kill'
        fi
        if  [ "_${verb}" = "_start" ]; then
            # TV Headend behaves better without authentication.
            (eval xfce4-terminal -T 'tvheadend' -x tvheadend --noacl) &
            /usr/bin/compton-trans -c -o 70
        fi
        ;;

        (usbdisks)
        if  [ "_${verb}" = "_start" ] || [ "_${verb}" = "_stop" ]; then
            sudo umount /snapdisks/banana
            sudo umount /snapdisks/tabasco
            sleep 3
            sudo hd-idle -t sdd  # banana
            sudo hd-idle -t sdc  # tabasco
        fi
        ;;

        #
        # Startup only.
        #

        (wallpaper)
        # My current desktop wallpaper (subject to change) is cropped
        # from a photo taken by someone else. The attribution notice
        # is self-documenting.
        #
        if  [ "_${verb}" = "_start" ]; then
            i3-msg "focus output \"${cmon}\""
            (sleep 5 && xdotool key Return) &
            url="https://commons.wikimedia.org/wiki/File:London_360%C2%B0_Panorama_from_the_London_Eye.jpg"
            echo ${url} | xclip
            text="Attribution:  Photo by Gregg M. Erickson, ${url}"
            echo "${text}" | dmenu -b -fn 'pango:DejaVu Sans 11'
            (sleep 5 && xdotool key Return) &
            text="Mouse right click the i3 status bar to show these texts again. The URL is available on the clipboard."
            text="${text} Photo is cropped 5760x1080."
            echo "${text}" | dmenu -b -fn 'pango:DejaVu Sans 11'
        fi
        ;;

        #
        # Shutdown only.
        #

        (VirtualBox)
        if  [ "_${verb}" = "_stop" ]; then
            if [ "$(VBoxManage list runningvms | wc -l)" -ne 0 ]; then
                # Running VMs must be shutdown manually.
                # Abandon shutdown completely to allow enough time.
                exit 0
            else
                # Zero VMs running, safe to kill VirtualBox Manager.
                i3-msg '[title="VirtualBox Manager$"] kill'
            fi
        fi
        ;;

        (marks)
        # Stop anything with a mark. This is gentle but there is no
        # housekeeping and data could be lost.
        if [ "_${verb}" = "_stop" ]; then
            marks="$(i3-msg -t get_marks)"
            # shellcheck disable=2001
            for m in $(echo "${marks}" | sed 's/[],"\[]/ /g'); do
                i3-msg --quiet "[con_mark=\"${m}\"] kill"
                sleep 0.5
            done
        fi
        ;;

        (everything)
        # Safely start or stop everything listed in proper sequence.
        # To proceed press OK or wait for the short timeout to expire.
        # Ensure the dialog appears on the primary monitor.
        # The file watcher must be started first, the rest are optional.
        if  [ "_${verb}" = "_start" ]; then
            i3-msg "focus output ${cmon}"
            xdotool mousemove --sync --clearmodifiers 2880 384; sleep 1
            yad --title="Startup in 7s ..." --mouse --timeout=7 --timeout-indicator=top
            if  [ "$?" -ne 1 ]; then
                eval "$0 start filewatcher"
                eval "$0 start tvheadend"
                eval "$0 stop usbdisks" # Yes, spin them down!
                eval "$0 start wallpaper"
            else
                exit 0
            fi
	    yad --title="Startup complete." --timeout=3 --timeout-indicator=top
        fi
        if  [ "_${verb}" = "_stop" ]; then
            i3-msg "focus output ${cmon}"
            xdotool mousemove --sync --clearmodifiers 2880 384; sleep 1
            yad --title="Shutdown in 7s ..." --mouse --timeout=7 --timeout-indicator=top
            if  [ "$?" -ne 1 ]; then
                eval "$0 stop VirtualBox"
                eval "$0 stop tvheadend"
                eval "$0 stop marks"
                eval "$0 stop filewatcher"
                eval "$0 stop usbdisks"
            else
                exit 0
            fi
            yad --title="Shutdown complete." --timeout=3 --timeout-indicator=top
            if  [ "$?" -ne 1 ]; then
                xfce4-panel --quit && sleep 0.5 && xfce4-session-logout --logout
            else
                exit 0
            fi
        fi
        ;;

    esac
done

#
# Done.
#
