#!/bin/bash
#
# Display off/on.
#
# Requires i3-mouse for setmouse, xdotool.
#

setdisplay ()
{
    case "$1" in
        # Sleep the display using the keyboard or console, not the
        # mouse.
        (sleep|off)
        xdotool mousemove --clearmodifiers 2048 128
        i3-mouse disable
        sleep 3s
        xset s blank
        xset dpms 0 0 0
        xset dpms force off
        ;;
        # Wake the display using the keyboard or console, not the
        # mouse.
        (wake|on)
        i3-mouse enable
        xdotool mousemove --clearmodifiers 2048 128
        xset s off
        xset -dpms
        ;;
        (*)
        ;;
    esac
}

setdisplay "$1"

#
# Done.
#
