#!/bin/bash
#
# i3-status

i3status "$@" | while :
do
    read line
    port=$(sudo ufw status numbered | egrep -c "192.168.1.33.*.*ALLOW IN*")
    live=$(lsof /dev/video0 | awk '{print $1}' | grep -v COMMAND | uniq | sed 's/skypeforl*/skype/g')
    live=${live:-'idle'}
    mute2=$(pactl list sources | grep -A 7 TeckNet-02.analog-mono | grep -c 'Mute: no')
    mute3=$(pactl list sources | grep -A 7  alsa_input.pci-0000_00_1b.0.analog-stereo | grep -c 'Mute: no')
    marks=$(i3-msg -t get_marks | sed 's:\"::g')
    echo "${marks} | Cam ${live} Mic ${mute2} | Mic ${mute3} | ssh ${port} | ${line}" || exit 1
done

#
# Done.
#
