#!/bin/bash
#
# i3-status

i3status "$@" | while :
do
    read line
    port22=$(sudo ufw status numbered | egrep -c "192.168.1.33.*22.*ALLOW.*IN.*Anywhere")
    mute2=$(pactl list sources | grep -A 7 TeckNet-02.analog-mono | grep -c 'Mute: no')
    mute3=$(pactl list sources | grep -A 7  alsa_input.pci-0000_00_1b.0.analog-stereo | grep -c 'Mute: no')
    marks=$(i3-msg -t get_marks | sed 's:\"::g')
    echo "${marks} | Mic ${mute2} ${mute3} | ssh ${port22} | ${line}" || exit 1
done

#
# Done.
#
