#!/bin/bash
#
# i3-wrapper
#
# - This script and its companion scripts (i3-{apps, keyboard, mouse,
# - display, status, mode} together with a Makefile provide functions
# - that support my way of working.
#
# - This script uses a dmenu to enter commands that are typically two
# - or three characters long. Commands are written to a magic file and
# - each write triggers evaluation of the file contents. The mechanism
# - supports remote writers seamlessly.
#

#
# The wrapper Interface is a frequently modified magic file in shared
# memory.
#
dir=/dev/shm/${USER}/i3
file=command

#
# Label the (L)eft (C)entre (R)ight (MON)itors.
# My three monitors were arranged thus: [HDMI2] [HDMI1] [VGA1].
# Use 'xrandr' with no arguments to list monitor names and geometry.
#
lmon=HDMI2
cmon=HDMI1
rmon=HDMI2 ### VGA1

#
# Pulseaudio sinks (outputs) and sources ((inputs).
#
# - See dot-config-i3-config for the matching i3 variables.
#
analogaudiosink=alsa_output.pci-0000_00_1b.0.analog-stereo
bluetoothaudiosink=bluez_sink.00_01_01_00_12_CB
hdmiaudiosink=alsa_output.pci-0000_00_03.0.hdmi-stereo
usbaudiosink=alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo
#
export webcamaudiosource=alsa_input.usb-Alcor_Micro__Corp._TeckNet-02.analog-mono
export analogaudiosource=alsa_input.pci-0000_00_1b.0.analog-stereo
export usbaudiosource=alsa_input.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-mono

#
# The timeout in seconds for the main dynamic menu. Upon expiry,
# whatever has been entered wil be treated as a command to be
# executed. Try to reduce the timeout duration such that user has no
# need to press Enter. Start at 5 seconds.
#
export commandtimeout=4

#
# Focus or launch a program.
#
# EITHER switch focus to the running program matching on $1=$2, OR
# launch $5 with arguments ${@:6} on workspace $3 and output $4.
#
focus ()
{
    case "$1" in
        # Attempt to match the running program and obtain its window id.
        (instance)
        W=$(xdotool search --classname "$2" | head -1) ;;
        (class)
        W=$(xdotool search --class "$2" | head -1) ;;
        (title)
        W=$(xdotool search --name "$2" | head -1) ;;
        (*)
        W='' ;;
    esac

    if [ -z "$W" ]; then
        if [ $# -ge 5 ]; then
            # Change to the specified workspace and launch from there.
            # Set $3 'none' to stay on current workspace.
            if [ "$3" == 'none' ]; then
                i3-msg "exec ${*:5};"
            else
                i3-msg "workspace $3; exec ${*:5};"
            fi
            # Marks are typically allocated with "for_window", but
            # here is easier.
            i3_unique_mark
            # Change to the specified output when the window appears.
            # Set $4 'none' to stay on current output.
            case "$4" in
                (${lmon}|${cmon}|${rmon})
                sleep 0.3
                i3-msg "move workspace to output $4"
                ;;
            esac
        fi
    else
        # Focus the program.
        i3-msg "workspace $3"
    fi
}

#
# Scratchpad (drop down) terminal.
#
i3dd()
{
    # Only one key binding is required, the first keypress performs
    # initialisation and hides the terminal again.
    if [ "_$(xdotool search --classname "Scratchpad" | head -1)"  = "_" ]; then
        xfce4-terminal -T Scratchpad &
        sleep 1
        i3_unique_mark
        # Set the instance to identify the scratchpad.
        xdotool getwindowfocus set_window --classname "Scratchpad"
        i3-msg "[instance=\"Scratchpad\"] resize set 80 ppt 80 ppt"
        i3-msg "[instance=\"Scratchpad\"] move absolute position 2112 24"
        i3-msg "[instance=\"Scratchpad\"] move scratchpad"
    else
        i3-msg "focus output ${cmon}"
        i3-msg "[instance=\"Scratchpad\"] scratchpad show"
    fi
}

#
# Add a terminal (split h, side-by-side).
#
i3tt()
{
    i3-msg "split h"
    xfce4-terminal -T "xfce4-terminal" &
}

#
# Add a terminal (split v, stacked).
#
i3yy()
{
    i3-msg "split v"
    xfce4-terminal -T "xfce4-terminal" &
}

#
# Assign a unique mark.
#
i3_unique_mark()
{
    # Generate a random 2 digit mark.  Reject and retry if it matches
    # an assigned mark. The retry loop takes more time as the number
    # of marked containers approaches 100.
    while : ; do
        id=$((10#$(date +%N) % 100))
        id=$(printf "%02d" "${id}")
        count=$(for m in $(i3-msg -t get_marks | sed 's/,/\ /g');
                do echo "${m}"; done | grep -c "${id}")
        if [ "${count}" -eq 0 ]; then break; fi
    done
    sleep 1 # No need for caller to wait for the window.
    windowid=$(printf "0x%x" "$(xdotool getwindowfocus)")
    i3-msg "[id=\"${windowid}\"] mark --toggle \"${id}\""
    i3-msg "[con_mark=\"${id}\"] focus"
}

#
#  Focus the next mark in a circular list of single letter marks.
#
#  - There are two circular paths of length 3 and one of length 4
#    for a total of 10 marks: (A,B,C) (R,S,T) (W,X,Y,Z).
#
i3_cycle_marks()
{
    # Determine the single letter mark for the currently focused window.
    # Thanks to  u/jimbopouliot on r/i3wm (reddit) for 'jq' improvement.
    # https://www.reddit.com/r/i3wm/comments/bcck1t/how_to_alttab_for_groups_of_windows/
    mark=$(i3-msg -t get_tree | jq '.. | objects | select(.focused) | .marks[] | select(match("^[ABCRSTWXYZ]$"))')

    # Conveniently, the letter is enclosed by double quotes.
    case "${mark}" in
        (\"A\") i3-msg "[ con_mark=\"B\" ] focus" ;;
        (\"B\") i3-msg "[ con_mark=\"C\" ] focus" ;;
        (\"C\") i3-msg "[ con_mark=\"A\" ] focus" ;;

        (\"R\") i3-msg "[ con_mark=\"S\" ] focus" ;;
        (\"S\") i3-msg "[ con_mark=\"T\" ] focus" ;;
        (\"T\") i3-msg "[ con_mark=\"R\" ] focus" ;;

        (\"W\") i3-msg "[ con_mark=\"X\" ] focus" ;;
        (\"X\") i3-msg "[ con_mark=\"Y\" ] focus" ;;
        (\"Y\") i3-msg "[ con_mark=\"Z\" ] focus" ;;
        (\"Z\") i3-msg "[ con_mark=\"W\" ] focus" ;;

        (*)
        # If the mark is absent the window id does not change.
        # If focus succeeds stop, else try again with the next mark.
        id=$(xdotool getwindowfocus)
        i3-msg "[ con_mark=\"A\" ] focus"
        windowid=$(xdotool getwindowfocus)
        if [ "${id}" = "${windowid}" ]; then
            id="${windowid}"
            i3-msg "[ con_mark=\"R\" ] focus"
            windowid=$(xdotool getwindowfocus)
            if [ "${id}" = "${windowid}" ]; then
                i3-msg "[ con_mark=\"X\" ] focus"
            fi
        fi
    esac
}

#
# Create a workspace with three side-by-side terminals inside if none
# exists, othewise visit the workspace. The name of the workspace is
# the command alias. Inspired by:
# https://www.reddit.com/r/i3wm/comments/bjw151/i3_reading_window/
#
i3_triple_terminal_workspace()
{
    cws=$(i3-msg -t get_workspaces | jq '.[] | .name,.focused' | \
                 grep true -B1 | grep -v true)
    tws=$(i3-msg -t get_workspaces | jq '.[] | .name' | grep -c "$1")
    if [ "${cws}" != "\"$1\"" ]; then
        i3-msg "workspace $1"
        if [ "${tws}" -eq 0 ]; then
            # One subshell.  The marks and the focusing are required.
            ( xfce4-terminal -T "xfce4-terminal"
              xfce4-terminal -T "xfce4-terminal"
              xfce4-terminal -T "xfce4-terminal"
              i3-msg "focus left"
              i3-msg "focus left"
            ) &
        fi
    fi
}

#
# Subroutine for emacs frames and chrome windows.
#
# $1 (e[0-9] g[0-9] instance)
# $2 emacs24, chrome
# $3 emacs24 -rv, google-chrome
# $4 emacsclient.emacs24 -c, google-chrome --new-window
#
i3emgc ()
{
    cws=$(i3-msg -t get_workspaces | jq '.[] | .name,.focused' | grep true -B1 | grep -v true)
    arg="$1"
    # shellcheck disable=2086
    if [ "$(pgrep -c $2)" -eq 0 ]; then
        if  [ "${cws}" != "${arg}" ]; then
            # shellcheck disable=2086
            i3-msg "workspace ${arg}, exec sleep 1"
        fi
        i3-msg "exec  $3"
    else
        # shellcheck disable=2086
        count=$(i3-msg -t get_workspaces | jq 'map(.name)' | grep -c \"${arg}\")
        if [ "${count}" -eq 0 ]; then
            if  [ "${cws}" != "${arg}" ]; then
                i3-msg "workspace ${arg}, exec sleep 1"
            fi
            i3-msg "exec $4"
        else
            i3-msg "workspace ${arg}"
        fi
    fi
}

i3_lower_digit()
{
    case "$1" in
        # Emacs frames.
        # Use 'em' to add another frame alongside an existing one.
        (e[0-9])
        i3emgc "$1" 'emacs24' 'emacs24 -rv' 'emacsclient.emacs24 -c'
        ;;
        # Chrome windows.
        # Use 'gc' to add another window alongside an existing one.
        (g[0-9])
        i3emgc "$1" 'chrome' 'google-chrome' \
               ' google-chrome --new-window'
        ;;
        # Create a workspace with an Emacs frame and one or two
        # terminals.  The workspace name will match e[0-9].
        # Examples: t5 == e5 then tt.  y3 == e3 then tt then yy.
        (t[0-9])
        i3_lower_digit "e${1:1}" && sleep 0.8 && i3_lower_lower_hard 'tt'
        ;;
        (y[0-9])
        i3_lower_digit "e${1:1}" && sleep 0.8 && i3_lower_lower_hard 'ty'
        ;;
        # Create a workspace with an Emacs frame and a Google Chrome
        # window.  The workspace name will match e[0-9].  The letter 'w'
        # has 'www' mnemonic. The delay is a safety net.
        (w[0-9])
        i3_lower_digit "e${1:1}"
        sleep 3
        google-chrome --new-window
        ;;
        # Samsung phone.
        (s7)
        focus title "SM-G930F" 's7' ${lmon} xfce4-terminal -T "SM-G930F"
        ;;
    esac
}

i3_lower_lower_easy()
{
    case "$1" in
        (ff)
        focus instance Navigator 'ff' ${cmon} firefox ;;
        (tb)
        focus class Thunderbird 'tb' ${lmon} thunderbird ;;

        # Does the user want this program to launch in a dedicated
        # workspace or in the current workspace?
        (th)
        focus title 'File Manager' 'th' ${rmon} \
              exo-open --launch FileManager "${HOME}/1/Downloads" ;;
        (tn)
        focus title 'File Manager' 'tn' 'none' \
              exo-open --launch FileManager "${HOME}/1/Downloads" ;;

        (sk)
        focus instance skype 'sk' ${rmon} /snap/bin/skype ;;
        (ws)
        focus instance wireshark 'ws' ${cmon} wireshark ;;
        (sy)
        focus instance synaptic 'sy' ${lmon} synaptic-pkexec ;;

        (pp)
        focus title "LibreOffice Impress"  'pp' 'none'   libreoffice --impress ;;
        (ss)
        focus title "LibreOffice Calc"  'ss' 'none'  libreoffice --calc ;;
        (ww)
        focus title "LibreOffice Writer"  'ww' 'none'   libreoffice --writer ;;

        (fp)
        focus class ffplay 'fp' ;;    # launched by command line.
        (mp)
        focus class mpv 'mp' ;;   # launched by 'tvheadend'.

        (vp)
        focus instance vlc 'vp' ${lmon} /snap/bin/vlc ;;
        (hb)
        focus instance handbrake 'hb' ${cmon} \
              "${HOME}/Programs/scripts//handbrake-cpulimit" ;;
        (os)
        focus instance openshot 'os'  ${cmon} openshot ;;

        (mu)
        focus class 'Spotify'  'mu' ${lmon} /snap/bin/spotify ;;

        (vb)
        focus title 'Oracle VM VirtualBox' 'vb' ${cmon} virtualbox ;;
    esac
}

#
# These commands don't quite follow the focus-else-launch pattern of
# the commands designated 'easy'.
i3_lower_lower_hard()
{
    case "$1" in
        # 1. Terminal in the current workspace. Split is top-bottom.
        # 2. Terminal in the current workspace. Split is left-right.
        # 3. Dropdown terminal (strictly: a scratchpad terminal).
        (tt)
        i3tt ;;
        (yy)
        i3yy ;;
        (dd)
        i3dd ;;

        # A container layout : ""tt' then 'yy' => 'ty'.
        (ty)
        i3tt && sleep 2 && i3yy ;;

        # Use these to add an instance into an existing workspace.
        (em)
        i3-msg "exec emacsclient.emacs24 -c" ;;
        (gc)
        i3-msg "exec google-chrome --new-window" ;;

        # These simply don't fit the easy launch-or-focus template.
        (sg)
        xfce4-screenshooter -d 2 ;;
        (wc)
        eval cheese >/dev/null 2>&1 ;;

        # Eye candy. Reveal background. KISS.
        (zz)
        i3-msg "focus output \"${lmon}\", workspace \"$1\"" ;;
        (xx)
        i3-msg "focus output \"${cmon}\", workspace \"$1\"" ;;
        (cc)
        i3-msg "focus output \"${rmon}\", workspace \"$1\"" ;;

        # Visit the eponymous workspace if it exists, otherwise create
        # the workspace and launch three side-by-side terminals there.
        ([a-z][a-z]) i3_triple_terminal_workspace "$1" ;;
    esac
}

#
# 1. Manage containers with marks. 2. Manage headphone volumes.
#
i3_digit_digits()
{
    case "$1" in
        ([9][0-9][0-9])
        i3_nine_hundreds "$1"  # Delegate these for a tidy function.
        ;;
        ([4][0-9][0-9])
        arg="${1:1:2}"  # Green jack volume as a percentage.
        pactl set-sink-volume  ${analogaudiosink} "${arg}%"
        ;;
        ([3][0-9][0-9])
        arg="${1:1:2}"  # HDMI volume as a percentage.
        pactl set-sink-volume  ${hdmiaudiosink} "${arg}%"
        ;;
        ([2][0-9][0-9])
        arg="${1:1:2}"  # Bluetooth volume as a percentage.
        pactl set-sink-volume  ${bluetoothaudiosink} "${arg}%"
        ;;
        ([1][0-9][0-9])
        arg="${1:1:2}"  # USB volume as a percentage.
        pactl set-sink-volume "${usbaudiosink}%"
        ;;
        ([05][0-9][0-9])
        # Swap this container with the matching marked container.
        # Prefix is 0 for numpad or 5 for voice, then two-digit mark.
        arg="${1:1:2}"
        i3-msg "swap container with mark ${arg}"
        say "swap with mark ${arg}"
        ;;
        ([0-9][0-9])
        # Visit a two-digit mark using numpad or voice.
        # This case must come after all the three-digit cases.
        arg="${1:0:2}"
        i3-msg "[con_mark=\"${arg}\"] focus"
        say "focus mark ${arg}"
        ;;
    esac
}

#
# A very small set of relevant numeric commands. Prefer mnemonic
# values for voice commands over ease of typing.
#
i3_nine_hundreds()
{
    case "$1" in
        (999)
        i3_unique_mark  # Apply a mark.
        ;;
        (911|910)
        # 1/0 = Stop/Start AutoVoice = Mute/Unmute  USB  microphone.
        # Audio stream bitrate should decrease by 128kps when muted.
        pactl set-source-mute $usbaudiosource "${1:2:1}"
        ;;
    esac
}

#
# As of 2019-11-03, reliable numeric voice commands are a thing so we
# can have some fun talking to the user.
#
say()
{
    "${HOME}/local/bin/speech-synthesis"  --play-en-GB "$1"
}

#
# Entry point for invoking a command alias supplied either directly
# via command line or indirectly via the file watcher.
#
start ()
{
    case "$1" in
        ([a-z][0-9])
        i3_lower_digit "$1"
        ;;
        ([a-z][a-z])
        i3_lower_lower_easy "$1"
        i3_lower_lower_hard "$1"
        ;;
        ([0-9]*)
        i3_digit_digits "$1"
        ;;
        (:*)
        eval "${HOME}/local/bin/i3-tasker" 'i3_generic' "$*"
        ;;
    esac
}

#
# When the file held in shared memory [ ${dir}/${file} ] changes, the
# file contents are passed into the i3wrapper as a command.  The
# typical command consists of a two or three character string but
# longer commands with argument lists are accepted; the former are
# called "command aliases" and the latter are assumed to be i3-msg
# commands.
#
# Don't call this directly. Called from i3filewatcher.
#
i3command ()
{
    cmd=$(cat "${dir}/${file}")
    start "${cmd}"
}

#
# File watcher.
#
# Create a file in shared memory, monitor it for changes, and when it
# changes, call i3wrapper with the file contents passed as argument.
#
# Don't call this directly. Called from i3-apps at startup.
#
i3filewatcher ()
{
    mkdir -p "${dir}"
    echo "--" > "${dir}/${file}"  # no-op
    exe=$(basename  "$0")
    xfce4-terminal -T "${exe}: file watcher" -x \
        inotify-hookable \
        --watch-files "${dir}/${file}" \
        --on-modify-command "$0 -s" &
}

#
# List all the keybindings.
#
# - 2019-06-07: bound to Primary+i (for info).
#
i3kb ()
{
    which i3-make && i3-make
    i3-msg [title=\"i3 key bindings\"] kill
    xfce4-terminal -T 'i3 key bindings' -e "less /dev/shm/$USER/i3/bindings" &
}

#
#  Provide a text entry command prompt for command aliases and command
#  numbers.
#
dashp ()
{
    # Yes, dmenu has the '-m <digit>" switch, but it's easier to do this:
    i3-msg "focus output ${cmon}"
    if [ "$1" != "help" ]; then
        # This branch is intended to be taken first.  In order to
        # reduce manual keystrokes, the Return key is pressed
        # automatically after three or four seconds.
        ( sleep $commandtimeout && \
              pgrep -c -f "dmenu -b -fn pango:DejaVu Sans 11 -p Command:" && \
              xdotool key Return) &
        # The menu is kept short because of the timeout. The user is
        # expected to type commands, but menu help is available.
        # You may prefer these menu items in the opposite order.
        list="cancel help"
    else
        # This branch is taken after choosing help. The menu is
        # displayed with a command list and does not timeout.
        list=$(egrep "\([a-zA-Z][a-zA-Z0-9]\)$" "$0" | sort | sed 's/[ ()]//g')
        list="cancel ${list}"
    fi
    # Numpad enters digits.
    numlockx on
    cmd=$(echo "${list}" | sed 's/\ /\n/g' | \
                 dmenu -b -fn 'pango:DejaVu Sans 11' -p 'Command: ')
    if [ "${cmd}" = "cancel" ]; then
        numlockx off
    elif [ "${cmd}" = "help" ]; then
        numlockx off
        dashp "help"
    else
        numlockx off
        echo "${cmd}" > "${dir}/${file}"
    fi
}

#
# Start here.
#
case ${XDG_CURRENT_DESKTOP} in
    (XFCE)
    case "$1" in
        # FIXME: This single dash option works, a double dash
        # equivalent doesn't, and I'm not sure why.
        (-s) i3command ;;
        # The command prompt writes to ${dir}/{file} instead of
        # calling i3wrapper with the command as its argument.
        (-p) dashp ;;
        # Verbosity over obscurity, not enough single letters.
        (--file-watcher) i3filewatcher ;;
        (--cycle-through-marks) i3_cycle_marks ;;
        (--unique-mark) i3_unique_mark ;;
        (--keyboard-binding-info) i3kb ;;
        # In production, do nothing here?
        (*) start "$@" ;;
    esac
    exit 0
    ;;
    (*)
    exit 2
    ;;
esac

#
# Done.
#
